export const LOGIN = "LOGIN"
export const LOGOUT = "LOGOUT"
export const SET_TOKEN = "SET_TOKEN"
export const GET_POSTS = "GET_POSTS"
export const UPDATE_DIMENSIONS = "UPDATE_DIMENSIONS"
export const GET_POST_BY_ID = "GET_POST_BY_ID"
export const TOGGLE_ADMIN_VIEW = "TOGGLE_ADMIN_VIEW"
export const SUPPRIMER_POST = "SUPPRIMER_POST"